export enum ResponseCode {
	SUCCESS = 'SUCCESS',
	BAD_REQUEST = 'BAD_REQUEST',
	DATA_NOT_FOUND = 'DATA_NOT_FOUND',
	ETC = 'ETC',
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

	//Auth
	ALREADY_REGISTERED_USER = 'ALREADY_REGISTERED_USER',
	NOT_REGISTERED_USER = 'NOT_REGISTERED_USER',
	UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',

	EXPIRED_VERIFICATION_CODE = 'EXPIRED_VERIFICATION_CODE',
	ALREADY_VERIFIED_EMAIL = 'ALREADY_VERIFIED_EMAIL',
	NOT_VERIFIED_EMAIL = 'NOT_VERIFIED_EMAIL',
	MAILER_ERROR = 'MAILER_ERROR',

	WRONG_EMAIL_OR_PASSWORD = 'WRONG_EMAIL_OR_PASSWORD',

	// Profile
	ALREADY_EXIST_NICKNAME = 'ALREADY_EXIST_NICKNAME',
	ALREADY_USER_PROFILE_EXIST = 'ALREADY_USER_PROFILE_EXIST',

	// Commons
	ALREADY_EXIST_GENRE = 'ALREADY_EXIST_GENRE',
}
