export enum ResponseCode {
	SUCCESS = 'SUCCESS',
	BAD_REQUEST = 'BAD_REQUEST',
	DATA_NOT_FOUND = 'DATA_NOT_FOUND',
	ETC = 'ETC',
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

	//Auth
	ALREADY_REGISTERED_USER = 'ALREADY_REGISTERED_USER',
	NOT_REGISTERED_USER = 'NOT_REGISTERED_USER',
	UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',

	EXPIRED_VERIFICATION_CODE = 'EXPIRED_VERIFICATION_CODE',
	ALREADY_VERIFIED_EMAIL = 'ALREADY_VERIFIED_EMAIL',
	NOT_VERIFIED_EMAIL = 'NOT_VERIFIED_EMAIL',
	MAILER_ERROR = 'MAILER_ERROR',

	WRONG_EMAIL_OR_PASSWORD = 'WRONG_EMAIL_OR_PASSWORD',

	// Profile
	PROFILE_NOT_EXIST = 'PROFILE_NOT_EXIST',
	ALREADY_EXIST_NICKNAME = 'ALREADY_EXIST_NICKNAME',
	ALREADY_USER_PROFILE_EXIST = 'ALREADY_USER_PROFILE_EXIST',

	// Commons
	UPLOAD_FILE_LIST_IS_EMPTY = 'UPLOAD_FILE_LIST_IS_EMPTY',
	NOT_UPLOADED_FILE = 'NOT_UPLOADED_FILE',
	IS_NOT_IMAGE_FILE = 'IS_NOT_IMAGE_FILE',
	ALREADY_EXIST_GENRE = 'ALREADY_EXIST_GENRE',
	NOT_REGISTERED_GENRE = 'NOT_REGISTERED_GENRE',

	// Story
	ALREADY_EXIST_STORY = 'ALREADY_EXIST_STORY',
	NOT_REGISTERED_STORY = 'NOT_REGISTERED_STORY',
	NOT_STORY_AUTHOR = 'NOT_STORY_AUTHOR',

	//Scene
	NOT_REGISTERED_SCENE = 'NOT_REGISTERED_SCENE',
}
