export enum ResponseCode {
	SUCCESS = 'SUCCESS',

	UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',
	DATA_NOT_FOUND = 'DATA_NOT_FOUND',
	NOT_REGISTERED_USER = 'NOT_REGISTERED_USER',
	WRONG_EMAIL_OR_PASSWORD = 'WRONG_EMAIL_OR_PASSWORD',
	ALREADY_VERIFIED_ACCOUNT = 'ALREADY_VERIFIED_ACCOUNT',
	ALREADY_REGISTERED_USER = 'ALREADY_REGISTERED_USER',
	NOT_VERIFIED_EMAIL = 'NOT_VERIFIED_EMAIL',

	ALREADY_EXIST_GENRE = 'ALREADY_EXIST_GENRE',

	ETC = 'ETC',
}
